dist: trusty
sudo: false
notifications:
  email: false
language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules
    - $HOME/.sdkman

before_install:
  # Install a later version of sbt-extras to support SBT >=1.0
  - curl -Ls https://git.io/sbt > ~/bin/sbt
  - chmod a+x ~/bin/sbt
  # sdkman helps to install different gradle versions
  # adding $HOME/.sdkman to cache would create an empty directory, which interferes with the initial installation
  - "[[ -d /home/travis/.sdkman/ ]] && [[ -d /home/travis/.sdkman/bin/ ]] || rm -rf /home/travis/.sdkman/"
  - curl -sL https://get.sdkman.io | bash
  - echo sdkman_auto_answer=true > /home/travis/.sdkman/etc/config
  - echo sdkman_auto_selfupdate=true >> $HOME/.sdkman/etc/config
  - source "/home/travis/.sdkman/bin/sdkman-init.sh"
  - unset _JAVA_OPTIONS
  - unset JAVA_HOME
  - java -Xmx32m -version
  - unset SBT_OPTS
  - export JAVA_OPTS="-Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M"

jobs:
  include:
    - stage: Node versions
      node_js: 6
      env: JDK=9
      script:
        - sdk list java | grep -o -m1 "$JDK\.[0-9\.]*-zulu"
        - sdk install java $(sdk list java | grep -o -m1 "$JDK\.[0-9\.]*-zulu") | true
        - java -version
        - npm test
        - npm run test-system
    -
      node_js: 8
      env: JDK=10
      script:
        - sdk list java | grep -o -m1 "$JDK\.[0-9\.]*-zulu"
        - sdk install java $(sdk list java | grep -o -m1 "$JDK\.[0-9\.]*-zulu") | true
        - java -version
        - npm test
        - npm run test-system
    -
      node_js: 10
      env: JDK=11
      script:
        - sdk list java | grep -o -m1 "$JDK\.[0-9\.]*-zulu"
        - sdk install java $(sdk list java | grep -o -m1 "$JDK\.[0-9\.]*-zulu") | true
        - java -version
        - npm test
        - npm run test-system
    - stage: Old and newer Java versions
      env: JDK=8
      script:
        - sdk list java | grep -o -m1 "$JDK\.[0-9\.]*-zulu"
        - sdk install java $(sdk list java | grep -o -m1 "$JDK\.[0-9\.]*-zulu") | true
        - java -version
        - npm test
        - npm run test-system
    -
      env: JDK=12
      script:
        - sudo apt-get update
        - sudo apt-get install -y openjdk-12-jdk
        - java -version
        - npm test
        - npm run test-system
    - stage: npm release
      if: branch = master
      node_js: "8" # This *has* to be the "build leader"
      script: skip
      after_success:
        - npx semantic-release
